### PR TITLE
Sponsor_FAQ section 

### PR DESCRIPTION
**Pull request by ishaan5199**
# Description

Added the Sponsor_FAQ component based on the design provided in the figma prototype

Dependencies : Nothing extra

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Browsers Tested on?

- [x] Chrome
- [x] Firefox
- [x] Edge

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have checked the responsiveness of the component I built
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by faiz-hasan11 — CHANGES_REQUESTED** [review]
- Top Background color is not black , check the color from figma and use that
- Remove usage of upper case in  both buttons
- The height of FAQ section with gradient is small , increase it , the content is looking crowded
- Add shadow to the dialog boxes
- In responsive screen , when all dialog boxes are aligned in center , give some padding from left and right for screen size between 1024px and 600px

**Review by faiz-hasan11 — CHANGES_REQUESTED** [review]
- Still Height of section is not increased
- For iPad Pro resolution add more padding to left and right

**Comment by ishaan5199** [comment]
> * Still Height of section is not increased
> * For iPad Pro resolution add more padding to left and right



> * Still Height of section is not increased
> * For iPad Pro resolution add more padding to left and right

ok on it

**Review by faiz-hasan11 — CHANGES_REQUESTED** [review]
- Dont decrease the height of top black section , just increase the height of gradient section
- As you decreased the size of top black section , button is being dragged to gradient section in some responsive screens , fix it

**Review by faiz-hasan11 — DISMISSED** [review]
- Background Gradient is not matching
- Increase the Height of Top Black Section
- Increase the Font Size of "Want to be a Sponsor"

**Review by joshi008 — APPROVED** [review]
Good work!!!

**Pull request merged**
