### PR TITLE
Speakers_section

### LINKED ISSUE #5: Landing Page - Section 3.5 - Speakers section
**Is your feature request related to a problem? Please describe.**
No, its the initial website building part.

**Describe the solution you'd like**
Section-3.5:
* Design needs improvement as the image of one speaker is visible at a gance which would be bad for a first time viewer.
* Coordinate with designer for a new design
* Implement all the designs with the current color scheme and fot styling of the figma.

**Describe alternatives you've considered**
Discuss the design and its alternatives with your project maintainers and the designing team.

### PR DESCRIPTION
**Pull request by jaswanthpallavolu**
# Speakers_section

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Closes #5 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Browsers Tested on?

- [1 ] Chrome
- [1 ] Firefox
- [ ] Edge

# Checklist:

- [1 ] My code follows the style guidelines of this project
- [1 ] I have performed a self-review of my own code
- [1 ] I have checked the responsiveness of the component I built
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ 1] My changes generate no new warnings

### CODE REVIEW

**Comment by joshi008** [comment]
* Font of Our Speakers does not match with the style on figma. Please correct it.
image

* Design is not responding, it goes out of page when seen in some of the screen sizes.
image

**Review by faiz-hasan11 — CHANGES_REQUESTED** [review]
- Our Speakers font is different
- The content look very crowded , add some padding 
- Add border to image
- Give some space between Youtube Live and the Line
- The section is not responsive for various screen , please redo it

**Review by faiz-hasan11 — DISMISSED** [review]
- Padding from left and right is not even , content looks shifted to right
- Decrease content size or add more padding in responsive design
- For iPad Pro , dont align content in single line

**Comment by faiz-hasan11** [comment]
Development branch has been updated , kindly take a pull and then start working

**Review by joshi008 — CHANGES_REQUESTED** [review]
From 1020 to 880 screen size, the width of the card is too large. Try to make it little small and center it.
image

**Comment by faiz-hasan11** [comment]
Kindly take a pull , the development branch has been updated

**Review by joshi008 — APPROVED** [review]

**Pull request merged**
