### PR TITLE
Added Footer Component- Responsive

### LINKED ISSUE #9: Landing Page - Section 7 - Footer
**Is your feature request related to a problem? Please describe.**
No, its the initial website building part.

**Describe the solution you'd like**
Section-7 of the Landing Page:
* Replicate the footer design as in figma file. 
* Direct user to iiitkottayam social handels for the testing period.

**Describe alternatives you've considered**
Discuss the design alternatives with designers and project maintainers.

**Additional context**
Prototype: https://www.figma.com/proto/4a8ZglxR98YOEQpmXu93Ng/Dhruva-team-library?page-id=0%3A1&node-id=312%3A18&viewport=241%2C48%2C0.2&scaling=min-zoom

### PR DESCRIPTION
**Pull request by shashank1503-cipher**
# Description

Added the responsive footer component as asked. Requires react-icons.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Browsers Tested on?

- Chrome
- Firefox
- Edge

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have checked the responsiveness of the component I built
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by starwiz-7** [comment]
@shashank1503-cipher Can you add the footer to the index.js file so that we can preview it and then merge it.

**Comment by shashank1503-cipher** [comment]
Yeah sure

**Comment by shashank1503-cipher** [comment]
Added Footer to index.js

**Comment by shashank1503-cipher** [comment]
package-lock.json was showing some changes.....i didn't commit it when i was changing the index.js file......i committed it afterwards so that it's easily revertable

**Comment by faiz-hasan11** [comment]
Hey , Your betalabs-horizontal.png image is missing thats why deployment has crashed for unknown import

**Comment by faiz-hasan11** [comment]
- There are issues with responsive design. Please recheck.
- The heart used in footer should be an emoji instead of icon so that its aligned along with the text
- The social icon tray should be more to the right.
- Increase Social Icon Size
- Align the BetaLabs Logo and Social Icon Tray in a straight line

**Review by faiz-hasan11 — COMMENTED** [review]
Make the beforesaid changes

**Comment by shashank1503-cipher** [comment]
Okay

**Comment by shashank1503-cipher** [comment]
Changed as required.........just have a look

**Comment by faiz-hasan11** [comment]
- Still there is problem with responsiveness for screen less than and around 600px
- Horizontal line missing the above the text

**Comment by shashank1503-cipher** [comment]
Changed as required

**Comment by joshi008** [comment]
@shashank1503-cipher , Could you resolve the conflicts. And once see the merged thing is perfect (test in your localhost as well), because we got a PR from Sarthak.

**Comment by shashank1503-cipher** [comment]
Ya okay it happened because of removal of coming soon.....on it

**Comment by joshi008** [comment]
A few responsive changes are there

**Comment by faiz-hasan11** [comment]
Take a pull from current development branch and merge your footer in it at your local . Resolve all conflicts and then push the code.

**Comment by shashank1503-cipher** [comment]
Resolved the responsive bug I encountered

**Review by joshi008 — APPROVED** [review]
Looks good to me

**Pull request merged**
