### PR TITLE
Landing Page - Section 5 - Prizes and Sponsors

### LINKED ISSUE #7: Landing Page - Section 5 - Prizes and Sponsors
**Is your feature request related to a problem? Please describe.**
No, its the initial website building part.

**Describe the solution you'd like**
Section-5 of the Landing Page:
* Choose a gradient style of the background.
* Make grid or anything you like for the prizes and sponsors in the prototype. 
* Make sure the website is responsive and the grids fall back to one over another in mobile view.

**Describe alternatives you've considered**
Discuss the design alternatives with project maintainers and designers.

**Additional context**
Prototype: https://www.figma.com/proto/4a8ZglxR98YOEQpmXu93Ng/Dhruva-team-library?page-id=0%3A1&node-id=312%3A18&viewport=241%2C48%2C0.2&scaling=min-zoom

### PR DESCRIPTION
**Pull request by Anshu1882000**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

# Browsers Tested on?

- [x] Chrome
- [ ] Firefox
- [ ] Edge

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have checked the responsiveness of the component I built
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by joshi008 — CHANGES_REQUESTED** [review]
image

**Comment by faiz-hasan11** [comment]
Kindly have a look on above errors

**Comment by AVS18** [comment]
Just to make sure, you get no warnings while running the react-app in local. vercel will block the deployments even if there is a single warning. It can be ensured to deploy if you can see something like this

image

**Review by faiz-hasan11 — DISMISSED** [review]
- Change color of Prizes to White
- Grid Lines missing between sponsors

**Comment by Anshu1882000** [comment]
Those grid lines I have intentionally not kept because it's looking much better without those lines plus including those we have to give extra margin around those line and on smaller devices it would just be a waste of space and force other contents to fit within a much smaller space than earlier ( based on my design sense ). If u still want those lines let me know.

**Comment by faiz-hasan11** [comment]
Development branch has been updated , kindly take a pull and then start working

**Review by joshi008 — CHANGES_REQUESTED** [review]
Kindly pull the latest code before doing any edits, since we got another PR merged recently.

* The font of Prizes do not look similar to the  design. Make the font color to white and check once. Otherwise find other ways to do so.
* There is less spacing below the end of the section
image

**Comment by faiz-hasan11** [comment]
Please recheck the font of "Prizes"

**Comment by Anshu1882000** [comment]
font I have used from the global CSS I haven't explicitly defined it. Please go through my code once.

**Comment by faiz-hasan11** [comment]
Avoid using strokes width to add increase font line width , instead try to shift the content . Take help from About Section 15th and 18th date styles

**Review by joshi008 — CHANGES_REQUESTED** [review]
* Color choosen for background gradient does not matches the color in the figma file.
image

* Font size of Prizes in mobile version is too much..
image

* The companies are colliding into each another in mobile view. 
image

* And please make design such that even if we have more companies in the future sponsoring us.. then we could accomodate them. As in the figma design we have 4 companies in a row. Add 2 rows of 4 companies each, both in prizes and sponsors section. 

* In the mobile view make two or one companies displayed one below another.
  X X
  X X
  X X
like this or 
X
X
X
X
like this.

**Comment by faiz-hasan11** [comment]
Kindly take a pull , the development branch has been updated

**Comment by faiz-hasan11** [comment]
Development branch updated , take a pull and then work

**Review by joshi008 — APPROVED** [review]

**Pull request merged**
