### PR TITLE
404-added

### LINKED ISSUE #32: 404 Not found Page Creation on wrong url
**Is your feature request related to a problem? Please describe.**
No, its the initial website building part.

**Describe the solution you'd like**
404 not found page:
* Find out some good illustrations for our 404 page
* Make sure that the theme of the web page is maintained.
* 404 page should be rendered when the url does not exists in our directory, or we have no page to be rendered for it.

**Describe alternatives you've considered**
Discuss the design alternatives with designers and project maintainers.

**Additional context**
Design at https://www.figma.com/file/4a8ZglxR98YOEQpmXu93Ng/Dhruva-team-library?node-id=0%3A1

### PR DESCRIPTION
**Pull request by RaiLokesh**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Browsers Tested on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have checked the responsiveness of the component I built
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by joshi008 — CHANGES_REQUESTED** [review]
* On pressing home button, dont animate 404 text.
image

* Kindly use the pre-build button for home rather than creating a new button.
image

**Comment by faiz-hasan11** [comment]
Capture

**Comment by faiz-hasan11** [comment]
Whole UI has been distorted please recheck

**Comment by faiz-hasan11** [comment]
If possible decrease the box size in responsive screens

**Comment by joshi008** [comment]
Kindly also make the font color as brighter white rather than dull white

**Comment by faiz-hasan11** [comment]
- The button is tooo big in normal screen size , decrease it
- Increase font size of the text

**Review by joshi008 — APPROVED** [review]

**Pull request merged**
